src/Entity/Annee.php
<?php

namespace App\Entity;

use App\Repository\AnneeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AnneeRepository::class)]
class Annee
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $ordre = null;

    #[ORM\ManyToOne(inversedBy: 'annees')]
    private ?Parcours $parcours = null;

    /**
     * @var Collection<int, SemestreParcours>
     */
    #[ORM\OneToMany(mappedBy: 'annee', targetEntity: SemestreParcours::class)]
    private Collection $parcoursSemestre;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $codeApogeeEtapeAnnee = null;

    #[ORM\Column(length: 3, nullable: true)]
    private ?string $codeApogeeEtapeVersion = null;

    #[ORM\Column]
    private ?bool $isOuvert = true;

    #[ORM\OneToOne(inversedBy: 'anneeCopieAnneeUniversitaire', targetEntity: self::class, cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: true)]
    private ?self $anneeOrigineCopie = null;

    /** @var Annee $anneeCopieAnneeUniversitaire Référence l'élément copié, depuis l'année d'origine */
    #[ORM\OneToOne(mappedBy: 'anneeOrigineCopie', targetEntity: self::class, cascade: ['persist', 'remove'])]
    private ?self $anneeCopieAnneeUniversitaire = null;

    #[ORM\Column()]
    private int $capaciteAccueil = 0;

    #[ORM\Column]
    private ?bool $hasCapacite = true;

    #[ORM\Column]
    private ?bool $isProposeRecrutement = true;

    public function __construct()
    {
        $this->parcoursSemestre = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getOrdre(): ?int
    {
        return $this->ordre;
    }

    public function setOrdre(int $ordre): static
    {
        $this->ordre = $ordre;

        return $this;
    }

    public function getParcours(): ?Parcours
    {
        return $this->parcours;
    }

    public function setParcours(?Parcours $parcours): static
    {
        $this->parcours = $parcours;

        return $this;
    }

    /**
     * @return Collection<int, SemestreParcours>
     */
    public function getParcoursSemestre(): Collection
    {
        return $this->parcoursSemestre;
    }

    public function addParcoursSemestre(SemestreParcours $parcoursSemestre): static
    {
        if (!$this->parcoursSemestre->contains($parcoursSemestre)) {
            $this->parcoursSemestre->add($parcoursSemestre);
            $parcoursSemestre->setAnnee($this);
        }

        return $this;
    }

    public function removeParcoursSemestre(SemestreParcours $parcoursSemestre): static
    {
        if ($this->parcoursSemestre->removeElement($parcoursSemestre)) {
            // set the owning side to null (unless already changed)
            if ($parcoursSemestre->getOrdreAnnee() === $this) {
                $parcoursSemestre->setAnnee(null);
            }
        }

        return $this;
    }

    public function getCodeApogeeEtapeAnnee(): ?string
    {
        return $this->codeApogeeEtapeAnnee;
    }

    public function setCodeApogeeEtapeAnnee(?string $codeApogeeEtapeAnnee): static
    {
        $this->codeApogeeEtapeAnnee = $codeApogeeEtapeAnnee;

        return $this;
    }

    public function getCodeApogeeEtapeVersion(): ?string
    {
        return $this->codeApogeeEtapeVersion;
    }

    public function setCodeApogeeEtapeVersion(?string $codeApogeeEtapeVersion): static
    {
        $this->codeApogeeEtapeVersion = $codeApogeeEtapeVersion;

        return $this;
    }

    public function isOuvert(): ?bool
    {
        return $this->isOuvert;
    }

    public function setIsOuvert(bool $isOuvert): static
    {
        $this->isOuvert = $isOuvert;

        return $this;
    }

    public function getAnneeOrigineCopie(): ?self
    {
        return $this->anneeOrigineCopie;
    }

    public function setAnneeOrigineCopie(?self $anneeOrigineCopie): static
    {
        $this->anneeOrigineCopie = $anneeOrigineCopie;

        return $this;
    }

    public function getAnneeCopieAnneeUniversitaire(): ?self
    {
        return $this->anneeCopieAnneeUniversitaire;
    }

    public function setAnneeCopieAnneeUniversitaire(?self $anneeCopieAnneeUniversitaire): static
    {
        // unset the owning side of the relation if necessary
        if ($anneeCopieAnneeUniversitaire === null && $this->anneeCopieAnneeUniversitaire !== null) {
            $this->anneeCopieAnneeUniversitaire->setAnneeOrigineCopie(null);
        }

        // set the owning side of the relation if necessary
        if ($anneeCopieAnneeUniversitaire !== null && $anneeCopieAnneeUniversitaire->getAnneeOrigineCopie() !== $this) {
            $anneeCopieAnneeUniversitaire->setAnneeOrigineCopie($this);
        }

        $this->anneeCopieAnneeUniversitaire = $anneeCopieAnneeUniversitaire;

        return $this;
    }

    public function getCapaciteAccueil(): int
    {
        return $this->capaciteAccueil ?? 0;
    }

    public function setCapaciteAccueil(int $capaciteAccueil = 0): static
    {
        $this->capaciteAccueil = $capaciteAccueil;

        return $this;
    }

    public function hasCapacite(): ?bool
    {
        return $this->hasCapacite;
    }

    public function setHasCapacite(bool $hasCapacite): static
    {
        $this->hasCapacite = $hasCapacite;

        return $this;
    }

    public function isProposeRecrutement(): ?bool
    {
        return $this->isProposeRecrutement;
    }

    public function setIsProposeRecrutement(bool $isProposeRecrutement): static
    {
        $this->isProposeRecrutement = $isProposeRecrutement;

        return $this;
    }

    public function isValid(): bool
    {
        return $this->getParcours() !== null;
    }
}

src/Entity/User.php
<?php
/*
 * Copyright (c) 2023. | David Annebicque | ORéOF  - All Rights Reserved
 * @file /Users/davidannebicque/Sites/oreof/src/Entity/User.php
 * @author davidannebicque
 * @project oreof
 * @lastUpdate 25/02/2023 23:23
 */

namespace App\Entity;

use App\Repository\UserRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Groups('formation_json_versioning')]
    #[ORM\Column(length: 180, unique: true)]
    private ?string $username = null;

    #[ORM\Column]
    private array $roles = [];

    #[ORM\Column(nullable: true)]
    private ?string $password = null;

    #[ORM\ManyToOne(inversedBy: 'users')]
    private ?Etablissement $etablissement = null;

    #[ORM\OneToMany(mappedBy: 'directeur', targetEntity: Composante::class)]
    private Collection $composantes;

    #[ORM\OneToMany(mappedBy: 'responsableDpe', targetEntity: Composante::class)]
    private Collection $composanteResponsableDpe;

    #[ORM\OneToMany(mappedBy: 'responsableMention', targetEntity: Formation::class)]
    private Collection $formationsResponsableMention;

    #[ORM\Column(length: 50)]
    #[Groups(['fiche_matiere:read', 'parcours_json_versioning', 'fiche_matiere_versioning', 'formation_json_versioning'])]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    #[Groups(['fiche_matiere:read', 'parcours_json_versioning', 'fiche_matiere_versioning', 'formation_json_versioning'])]
    private ?string $prenom = null;

    #[ORM\Column(length: 255)]
    #[Groups(['fiche_matiere:read', 'parcours_json_versioning', 'fiche_matiere_versioning', 'formation_json_versioning'])]
    private ?string $email = null;

    #[ORM\Column]
    private ?bool $isEnable = false;

    #[ORM\Column]
    private ?bool $isValidDpe = false;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?DateTimeInterface $dateValideDpe = null;

    #[ORM\Column]
    private ?bool $isValideAdministration = false;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?DateTimeInterface $dateValideAdministration = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?DateTimeInterface $dateDemande = null;

    #[ORM\Column]
    private ?bool $isDeleted = false;

    #[Groups('formation_json_versioning')]
    #[ORM\Column(length: 50, nullable: true)]
    private ?string $civilite = null;

    #[Groups('formation_json_versioning')]
    #[ORM\Column(length: 10, nullable: true)]
    private ?string $telFixe = null;

    #[Groups('formation_json_versioning')]
    #[ORM\Column(length: 10, nullable: true)]
    private ?string $telPortable = null;

    #[ORM\OneToMany(mappedBy: 'destinataire', targetEntity: Notification::class)]
    private Collection $notifications;

    #[ORM\OneToMany(mappedBy: 'coResponsable', targetEntity: Parcours::class)]
    private Collection $coParcours;

    #[ORM\OneToMany(mappedBy: 'coResponsable', targetEntity: Formation::class)]
    private Collection $coFormations;

    #[ORM\ManyToOne]
    private ?Composante $composanteDemande = null;

    #[ORM\ManyToOne]
    private ?Etablissement $etablissementDemande = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Historique::class)]
    private Collection $historiques;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Commentaire::class)]
    private Collection $commentaires;

    /**
     * @var Collection<int, DpeDemande>
     */
    #[ORM\OneToMany(mappedBy: 'auteur', targetEntity: DpeDemande::class)]
    private Collection $dpeDemandes;

    /**
     * @var Collection<int, UserProfil>
     */
    #[ORM\OneToMany(mappedBy: 'user', targetEntity: UserProfil::class)]
    private Collection $userProfils;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $serviceDemande = null;

    #[ORM\OneToOne(mappedBy: 'user', targetEntity: UserNotificationPreference::class, cascade: ['persist', 'remove'])]
    private ?UserNotificationPreference $notificationPreference = null;

    /**
     * @var Collection<int, UserWorkflowNotificationSetting>
     */
    #[ORM\OneToMany(mappedBy: 'user', targetEntity: UserWorkflowNotificationSetting::class)]
    private Collection $userWorkflowNotificationSettings;

    /**
     * @var Collection<int, UserCategoryNotificationSetting>
     */
    #[ORM\OneToMany(mappedBy: 'user', targetEntity: UserCategoryNotificationSetting::class)]
    private Collection $userCategoryNotificationSettings;

    /**
     * @var Collection<int, ChangeParcours>
     */
    #[ORM\OneToMany(mappedBy: 'auteur', targetEntity: ChangeParcours::class)]
    private Collection $changeParcours;

    public function __construct()
    {
        $this->composantes = new ArrayCollection();
        $this->notifications = new ArrayCollection();
        $this->composanteResponsableDpe = new ArrayCollection();
        $this->formationsResponsableMention = new ArrayCollection();
        $this->coParcours = new ArrayCollection();
        $this->coFormations = new ArrayCollection();
        $this->historiques = new ArrayCollection();
        $this->commentaires = new ArrayCollection();
        $this->dpeDemandes = new ArrayCollection();
        $this->userProfils = new ArrayCollection();
        $this->userWorkflowNotificationSettings = new ArrayCollection();
        $this->userCategoryNotificationSettings = new ArrayCollection();
        $this->changeParcours = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_LECTEUR';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEtablissement(): ?Etablissement
    {
        return $this->etablissement;
    }

    public function setEtablissement(?Etablissement $etablissement): self
    {
        $this->etablissement = $etablissement;

        return $this;
    }

    /**
     * @return Collection<int, Composante>
     */
    public function getComposantes(): Collection
    {
        return $this->composantes;
    }

    public function addComposante(Composante $composante): self
    {
        if (!$this->composantes->contains($composante)) {
            $this->composantes->add($composante);
            $composante->setDirecteur($this);
        }

        return $this;
    }

    public function removeComposante(Composante $composante): self
    {
        // set the owning side to null (unless already changed)
        if ($this->composantes->removeElement($composante) && $composante->getDirecteur() === $this) {
            $composante->setDirecteur(null);
        }

        return $this;
    }

    public function getPrenom(): ?string
    {
        return ucwords(mb_strtolower($this->prenom));
    }

    public function setPrenom(?string $prenom): void
    {
        $this->prenom = $prenom;
    }

    public function getNom(): ?string
    {
        return mb_strtoupper($this->nom);
    }

    public function setNom(?string $nom): void
    {
        $this->nom = $nom;
    }

    #[Groups(['fiche_matiere:read'])]
    public function getDisplay(): string
    {
        return mb_strtoupper($this->getNom()).' '. ucwords(mb_strtolower($this->getPrenom()));
    }

    public function getAvatarInitiales(): ?string
    {
        return mb_strtoupper(mb_substr(trim($this->getPrenom()), 0, 1).mb_substr(trim($this->getNom()), 0, 1));
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function isIsEnable(): ?bool
    {
        return $this->isEnable;
    }

    public function setIsEnable(bool $isEnable): self
    {
        $this->isEnable = $isEnable;

        return $this;
    }

    public function isIsValidDpe(): ?bool
    {
        return $this->isValidDpe;
    }

    public function setIsValidDpe(bool $isValidDpe): self
    {
        $this->isValidDpe = $isValidDpe;

        return $this;
    }

    public function getDateValideDpe(): ?DateTimeInterface
    {
        return $this->dateValideDpe;
    }

    public function setDateValideDpe(DateTimeInterface $dateValideDpe): self
    {
        $this->dateValideDpe = $dateValideDpe;

        return $this;

templates/process_validation/_checkParcours.html.twig
<h3>Etat du parcours</h3>

<p>Vérification de l'état du parcours {{ objet.libelle }} :
    <span class="badge bg-{{ processData.valid == true ? 'success' : 'danger' }}">
{{ processData.valid == true ? "Parcours vérifié complet" : 'Parcours incomplet' }}
</span></p>
<p>Vous pouvez vérifier l'état ici :
    <button
            {{ stimulus_controller('modal', {
                size: 'lg',
                modalTitle: 'verifier.la.saisie.parcours.title'|trans({}, 'process'),
                modalUrl: path('app_parcours_state', {parcours:objet.id}) }) }}
            data-action="click->modal#openModal"
            class="btn btn-outline-success btn-sm"
            data-size="lg"
            data-bs-toggle="tooltip"
            data-bs-placement="bottom"
            title="{{ 'verifier.la.saisie.parcours.infobulle'|trans({}, 'process') }}"
    >
        <i class="fas fa-check"></i>
        <span> Vérifier la saisie</span>
    </button>
</p>

<h3>Fiches EC/matières du parcours</h3>
<table class="table">
    <thead>
    <tr>
        <th>Sem. / UE</th>
        <th>EC</th>
        <th>Libellé</th>
        <th>Etat de la fiche</th>
        <th>Voir et Valider</th>
    </tr>

    </thead>
    {% for val in processData.validation.fiches %}
        {% if val.fiche != null %}
            <tr>
                <td>{{ val.ec.ue.semestre.display }} {{ val.ec.ue.display(objet) }} </td>
                <td>{{ val.ec.code }}  {{ val.ec.libelle }}</td>
                <td>
                    {% if val.fiche != 'sans objet' %}
                        {{ val.fiche.libelle }}
                    {% endif %}
                </td>
                <td>
                    {% if val.fiche == 'sans objet' %}
                        <span class="badge bg-info">Non concerné</span>
                    {% else %}
                        {% if val.fiche != null and val.fiche.libelle != null %}
                            <span class="badge bg-success">Initiée</span>
                        {% elseif val.fiche != null and val.fiche.libelle == null %}
                            <span class="badge bg-warning">Non Initiée</span>
                        {% else %}
                            <span class="badge bg-danger">Manquante</span>
                        {% endif %}
                    {% endif %}
                </td>
                <td>
                    {% if val.fiche != 'sans objet' %}
                        <a href="{{ path('fiche_matiere_v2_voir', {slug:val.fiche.slug}) }}"
                           target="_blank"
                           class="btn btn-outline-info btn-sm">Voir la fiche EC/matière et valider</a>
                    {% endif %}
                </td>
            </tr>
        {% else %}
            <tr class="bg-warning">
                <td class="text-white">{{ val.ec.ue.semestre.display }} {{ val.ec.ue.display(objet) }} </td>
                <td class="text-white">{{ val.ec.code }} {{ val.ec.libelle }}</td>
                <td class="text-center text-white" colspan="3">EC sans fiche</td>
            </tr>
        {% endif %}
    {% endfor %}
</table>

{{ component('alerte', {type:'info', message: 'Une fiche est initiée si elle est composée d\'un libellé au minimum.'}) }}

templates/process_validation/_checkParcours_rf.html.twig
{{ include('process_validation/_checkParcours.html.twig') }}

templates/process_validation/_demande_non_ouverture.html.twig
{{ component('alerte', {
    type: 'info',
    message: ('demande.non.ouverture.alerte')|trans({}, 'process')|nl2br|raw
}) }}

<form action="{{ path('app_validation_demande_non_ouverture', {parcours:parcours.id}) }}" method="post"
      enctype="multipart/form-data">
    <p>
        <strong>{{ ('demande.non.ouverture.label')|trans({}, 'process') }}</strong>
        <i
                class="fal fa-question-circle ms-1"
                data-controller="tooltip"
                data-tooltip-placement-value="bottom"
                aria-label="{{ ('demande.non.ouverture.help')|trans({}, 'process') }}"
                data-bs-original-title="{{ ('demande.non.ouverture.help')|trans({}, 'process') }}"></i>
    </p>

    <div class="form-check mt-2">
        <input class="form-check-input" type="radio"
               required value="NON_OUVERTURE"
               id="modificationMCCCTexte"
               name="demandeNonOuverture">
        <label class="form-check-label" for="modificationMCCCTexte">
            <strong>{{ ('demande.non.ouverture.confirmation.label')|trans({'%parcours%': parcours.libelle}, 'process') }}</strong>
            <i
                    class="fal fa-question-circle ms-1"
                    data-controller="tooltip"
                    data-tooltip-placement-value="bottom"
                    aria-label="{{ ('demande.non.ouverture.confirmation.help')|trans({}, 'process') }}"
                    data-bs-original-title="{{ ('demande.non.ouverture.confirmation.help')|trans({}, 'process') }}"></i>
        </label>
    </div>

    <div>
        <label for="argumentaire_demande_non_ouverture"
               class="form-label"> {{ ('demande.non.ouverture.argumentaire.label')|trans({}, 'process') }}
            <span class="required"></span>
            <i class="fal fa-question-circle ms-1"
               data-controller="tooltip"
               data-tooltip-placement-value="bottom"
               aria-label="{{ ('demande.non.ouverture.argumentaire.help')|trans({}, 'process') }}"
               data-bs-original-title="{{ ('demande.non.ouverture.argumentaire.help')|trans({}, 'process') }}"></i>
        </label>
        <textarea name="argumentaire_demande_non_ouverture"
                  class="form-control"
                  required id="argumentaire_demande_non_ouverture"
                  rows="5"
        ></textarea>
    </div>


    <div class="mt-2">
        <button type="submit" class="btn btn-success"
                {{ stimulus_action('base','sauvegardeFormModal', 'click') }}
        >
            <i class="fal fa-floppy-disk"></i>
            {{ ('btn.demande.non.ouverture')|trans({}, 'process') }}
        </button>
    </div>
</form>

templates/process_validation/_demande_reouverture.html.twig
{{ component('alerte', {
    type: 'info',
    message: ('demande.reouverture.alerte')|trans({}, 'process')|nl2br|raw
}) }}

<form action="{{ path('app_validation_demande_reouverture', {parcours:parcours.id}) }}" method="post"
      enctype="multipart/form-data">
    <p>
        <strong>{{ ('demande.reouverture.label')|trans({}, 'process') }}</strong>
        <i
                class="fal fa-question-circle ms-1"
                data-controller="tooltip"
                data-tooltip-placement-value="bottom"
                aria-label="{{ ('demande.reouverture.help')|trans({}, 'process') }}"
                data-bs-original-title="{{ ('demande.reouverture.help')|trans({}, 'process') }}"></i>
    </p>
    <div class="form-check mt-2">
        <input class="form-check-input" type="radio" value="MODIFICATION_TEXTE" id="modificationTexte"
               required
               name="demandeReouverture">
        <label class="form-check-label" for="modificationTexte">
            <strong>{{ ('demande.reouverture.modification.texte.label')|trans({}, 'process') }}</strong>
            <i
                    class="fal fa-question-circle ms-1"
                    data-controller="tooltip"
                    data-tooltip-placement-value="bottom"
                    aria-label="{{ ('demande.reouverture.modification.texte.help')|trans({}, 'process') }}"
                    data-bs-original-title="{{ ('demande.reouverture.modification.texte.help')|trans({}, 'process') }}"></i>
        </label>
    </div>
    <div class="form-check mt-2">
        <input class="form-check-input" type="radio"
               required value="MODIFICATION_MCCC_TEXTE"
               id="modificationMCCCTexte"
               name="demandeReouverture">
        <label class="form-check-label" for="modificationMCCCTexte">
            <strong>{{ ('demande.reouverture.modification.mccc.texte.label')|trans({}, 'process') }}</strong>
            <i
                    class="fal fa-question-circle ms-1"
                    data-controller="tooltip"
                    data-tooltip-placement-value="bottom"
                    aria-label="{{ ('demande.reouverture.modification.mccc.texte.help')|trans({}, 'process') }}"
                    data-bs-original-title="{{ ('demande.reouverture.modification.mccc.texte.help')|trans({}, 'process') }}"></i>
        </label>
    </div>
    <twig:alerte type="warning" message="Une ouverture avec CFVU implique que la publication des modifications sur les textes se fera à l'issue de la CFVU." />

    <div>
        <label for="argumentaire_demande_reouverture"
               class="form-label"> {{ ('demande.reouverture.modification.argumentaire.label')|trans({}, 'process') }}
            <span class="required"></span>
            <i class="fal fa-question-circle ms-1"
               data-controller="tooltip"
               data-tooltip-placement-value="bottom"
               aria-label="{{ ('demande.reouverture.modification.argumentaire.help')|trans({}, 'process') }}"
               data-bs-original-title="{{ ('demande.reouverture.modification.argumentaire.help')|trans({}, 'process') }}"></i>
        </label>
        <textarea name="argumentaire_demande_reouverture"
                  class="form-control"
                  required id="argumentaire_demande_reouverture"
                  rows="5"
        ></textarea>
    </div>


    <div class="mt-2">
        <button type="submit" class="btn btn-success"
                {{ stimulus_action('base','sauvegardeFormModal', 'click') }}
        >
            <i class="fal fa-floppy-disk"></i>
            {{ ('btn.demande.reouverture.modification')|trans({}, 'process') }}
        </button>
    </div>
</form>

templates/process_validation/_valide_fiche.html.twig
{{ component('alerte', {
    type: 'info',
    message: (process.label~'.valide.fiche.alerte')|trans({}, 'process')|nl2br|raw
}) }}

<form action="{{ path('app_validation_valider_fiche', {etape:etape, id:fiche.id}) }}" method="post"
      enctype="multipart/form-data">


    {% if process.check is defined and process.check == true %}
        {{ include('process_validation/_checkFiche_matiere.html.twig', {objet:fiche}) }}
    {% endif %}


    {% if (process.check is defined and process.check == true) %}
        {% if processData.valid == true %}
            <div class="mt-2">
                <button type="submit" class="btn btn-success"
                        {{ stimulus_action('base','sauvegardeFormModal', 'click') }}
                        data-action="live#emit"
                        data-event="valide"
                >
                    <i class="fal fa-floppy-disk"></i>
                    {{ ('btn.'~process.label~'.valide.'~processData.placeTexte)|trans({}, 'process') }}
                </button>
            </div>
        {% else %}
            {{ component('alerte', {
                type: 'danger',
                message: (process.label~'.valide.impossible.'~processData.placeTexte)|trans({}, 'process')
            }) }}
        {% endif %}
    {% else %}
        <div class="mt-2">
            <button type="submit" class="btn btn-success"
                    {{ stimulus_action('base','sauvegardeFormModal', 'click') }}
                    data-action="live#emit"
                    data-event="valide"
            >
                <i class="fal fa-floppy-disk"></i>
                {{ ('btn.'~process.label~'.valide')|trans({}, 'process') }}
            </button>
        </div>
    {% endif %}
</form>